FROM ubuntu:16.04
# https://docs.docker.com/engine/examples/running_ssh_service/

RUN apt-get update && apt-get install -qq -y openssh-server rsync sudo && \
    mkdir /var/run/sshd && \
    echo 'root:secret' | chpasswd && \
    sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    rm /bin/systemctl && ln -s /bin/true /bin/systemctl

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
